[ballerina.workflow.workflowConfig]
provider = "TEMPORAL"
url = "localhost:7233"
namespace = "default"

[ballerina.workflow.workflowConfig.params]
taskQueue = "CRM_SYNC_QUEUE"
maxConcurrentWorkflows = 100
