[package]
org = "ballerina"
name = "order_with_payment_sample"
version = "0.1.0"
distribution = "2201.13.0"

[[dependency]]
org = "ballerina"
name = "workflow"
version = "0.1.0"
repository="local"

[build-options]
observabilityIncluded = true
