[plugin]
id = "workflow-compiler-plugin"
class = "io.ballerina.stdlib.workflow.compiler.WorkflowCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/workflow-compiler-plugin-0.1.0.jar"
